//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conekt.XmlAuthentication.Web.App_UserControls.Xml.Authentication
{


	public partial class Account_Create
	{
	}
}
